# -*- coding: utf-8 -*-
"""03 investment portfolios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/mbk-dev/okama/blob/master/examples/03%20investment%20portfolios.ipynb

<a href="https://colab.research.google.com/github/mbk-dev/okama/blob/master/examples/03%20investment%20portfolios.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>

You can run the code examples in [Google Colab](https://colab.research.google.com/github/mbk-dev/okama/blob/master/examples/03%20investment%20portfolios.ipynb).

**To install the package:**
"""

!pip install okama

"""import okama and matplotlib packages ..."""

import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = [12.0, 6.0]

import okama as ok

"""**Portfolio** and **AssetList** can be helpful to learn about investment portfolio properties and to compare various portfolios with each other. With **AssetList** we can even compare portfolio with stocks, indexes and other types of financial assets (portfolio is just a special case of a financial asset).

In this tutorial we will learn how to:

- Create investment portfolio and see its basic properties
- Rebalancing strategy and asset allocation
- Risk metrics of the portfolio
- Accumulated return, CAGR and dividend yield
- Compare several portfolios
- Forecast portfolios performance

### Create an investment portfolio

Portfolios are quite similar to AssetList, but we should specify **weights** and **rebalancing** strategy.

All the arguments have default values and can be skipped.
"""

basic_portfolio = ok.Portfolio()
basic_portfolio

"""Default ticker is 'SPY.US'.  
Default currency is 'USD'.  
Default rebalancing period is one month.  
Inflation is included by default: `inflation=True`  
If portfolio has several assets they are included with equal weights by default.

Let’s create Rick Ferri's Lazy Three Fund Portfolio (40/40/20).  
Rebalancing period should be one year.
```
Rebalancing is the process by which an investor restores their portfolio to its target allocation by selling and buying assets. After rebalancing all the assets have original weights.
```

In the rebalancing strategy the **period** can be: 'month', 'year', 'half-year', 'quarter' or 'none' (for not rebalanced portfolios).
"""

rf3 = ok.Portfolio(
    ["BND.US", "VTI.US", "VXUS.US"],
    weights=[0.40, 0.40, 0.20],
    rebalancing_strategy=ok.Rebalance(period="year"),  # set the rebalancing period
)
rf3

"""Available history date range is defined by the assets.  
Each asset has it **first_date** and **last_date** which can be shown by `.assets_first_dates` and `.assets_last_dates`
"""

rf3.assets_first_dates

rf3.newest_asset

"""Here VXUS.US is a **stock with the shortest history** which is limiting the whole portfolio data."""

rf3.assets_last_dates

"""On the other hand, the **inflation** is limiting the data from the left side. If you need last month’s data to be included `inflation=False` should be used in Portfolio instantiating.

The ticker of portfolio is set automaticaly: **portfolio_8291.PF** (index is a random number).  
If you need a custom portfolio ticker you can use `symbol=` in portfolio instantiating or set it afterwards:
"""

rf3.symbol = "RF3_portfolio.PF"  # 'PF' namespace is reserved for portfolios.

"""Wealth index (Cumulative Wealth Index) is a time series that presents the value of portfolio over historical time period. The initial investment is 1000 points in a base currency."""

rf3.wealth_index.plot();

"""### Rebalancing strategy and asset allocaction

Table with original asset allocation can be seen with `.table`:
"""

rf3.table

"""RF3_portfolio has one year rebalancing period hence weight are subjects to change.  
It is possible to see assets eights time series with `.weights_ts`:
"""

rf3.weights_ts.plot();

"""let's create the same Rick Ferry portfolio, but without rebalancing (asset allocation will change and never return to the original weights)."""

rf3_no_rebalancing = ok.Portfolio(
    ["BND.US", "VTI.US", "VXUS.US"],
    weights=[0.40, 0.40, 0.20],
    rebalancing_strategy=ok.Rebalance(period="none"),
)

"""Now it's easy to see how the weights get out of control over time... and we end up with portfolio overweight in stocks."""

rf3_no_rebalancing.weights_ts.plot();

"""### Risk metrics of the portfolio

Portfolio has several methods to see risk metrics. By default with 'risk' we understand return time series standard deviation:

- risk_monthly (standard deviation for monthly rate of return time series)
- risk_annual (annualized standart deviation)
- semideviation_monthly (downside risk for monthly rate of return time series)
- semideviation_annual (annualized semideviation)
- get_var_historic (historic Value at Risk for the portfolio)
- get_cvar_historic (historic Conditional Value at Risk for the portfolio)
- drawdowns (percent decline from a previous peak)
- recovery_period (the longest recovery period after drawdown for the portfolio assets value)
"""

rf3.risk_annual.tail()  # aanualized values time series for standard deviation of return

rf3.semideviation_annual  # annualized value for downside risk

rf3.get_cvar_historic(time_frame=12, level=1)  # one year CVAR with confidence level 1%

"""Drawdowns (the percent decline from a previous peak) are easy to plot ..."""

rf3.drawdowns.plot();

rf3.drawdowns.nsmallest(5)  # 5 Biggest drawdowns

"""`reovery_period` highly related with Drawdowns. It shows the longest recovery periods for the portfolio value after drawdowns."""

rf3.recovery_period.nlargest() / 12  # we want it in years

"""### Accumulated return, CAGR and dividend yield

Portfolio has several metrics to measure the profits and return:

- wealth_index (the value of portfolio over historical time period)
- wealth_index_with_assets (wealth index with assets values)
- mean_return_monthly (arithmetic mean for the portfolio rate of return)
- mean_return_annual (annualized value for monthly mean)
- annual_return_ts (Annual rate of return time series)
- get_cagr (Compound Annual Growth Rate for a given trailing period)
- get_rolling_cagr (rolling CAGR with)
- get_cumulative_return (cumulative return over a given trailing period)
- get_rolling_cumulative_return (rolling cumulative return)
- dividend_yield (portfolio LTM dividend yield monthly time series)

Wealth index is a simpliest time series showing portfolio value growth (we have already seen it here). Sometimes it's worth to compare portfolio value growth with assets values.  
For that mean there is `wealth_index_with_assets` method.
"""

rf3.wealth_index_with_assets.plot();

"""Mean reaturn (arithmetic mean) for the portfolio is an annualized version of monthly mean:"""

rf3.mean_return_annual

"""It's always good to see how portfolio perform on annual basis. Annual rate of return time series show portfolio return for each calendar year:"""

rf3.annual_return_ts.tail()

"""... or in form of bar chart:"""

rf3.annual_return_ts.plot(kind="bar");

"""One of the most important return metrics is CAGR (Compound Annual Growth Rate). It can be seen for trailing periods (parameter *period* is in years):"""

rf3.get_cagr(period=5)  # portfolio is initiated with inflation=True. Hence, we see CAGR with mean inflation.

rf3.get_cagr(period=5, real=True)  # when real=True CAGR is adjusted for inflation (real CAGR)

"""Rolling CAGR for the portfolio is available with `get_rolling_cagr`:"""

rf3.get_rolling_cagr(
    window=12 * 2
).plot();  # window size is in moths. We have rolling 2 year CAGR here and rolling 2 year mean inflation ...

"""Cumulative return over a given trailing period can be calculated with `get_cumulative_return`. Period argument can be in years or YTD (Year To Date)."""

rf3.get_cumulative_return(
    period="YTD"
)  # Return since the beginning of the current calendar year and the inflation for the same period

rf3.get_cumulative_return(period=5)  # Cumulative return for the 5 years period

"""Cumulative rolling return can be helpfull in the same situation as rolling CAGR:"""

rf3.get_rolling_cumulative_return(window=12 * 5).plot();  # window size is in months (5 year cumulative return here)

"""Last twelve months (LTM) dividend yield is available with `dividend_yield` property."""

rf3.dividend_yield.plot();

"""Portfolio has monthly dividends time series:"""

rf3.dividends.tail()

"""Calendar year dividends sum time series for the portfolio:"""

rf3.dividends.resample("Y").sum().plot(kind="bar");

"""**Sharpe Ratio** was developed by Nobel laureate William F. Sharpe and is used to understand the return of an investment compared to its risk.

$$
S_p = \frac{R_p - R_f}{\sigma_p}
$$
$R_p$ - expected return of portfolio  
$R_f$ - risk-free rate of return  
$\sigma_p$ - portfolio risk (standard deviation of return)
"""

rf3.get_sharpe_ratio(rf_return=0.02)  # risk-free rate is 2% here

"""Finally the easiest way to see the portfolio basic properties is with `describe`:"""

rf3.describe()

"""### Compare several portfolios

Portfolio is a kind of financial asset and can be included in AssetList to compare with other portfolios (assets or benchmarks).

Lets create  Rick Ferri 4 assets portfolio and compare the behaviour with 3 assets portfolio.
"""

assets = ["BND.US", "VTI.US", "VXUS.US", "VNQ.US"]  # Vanguard REIT ETF (VNQ) is added.
weights = [0.40, 0.30, 0.24, 0.06]

"""To compare properly with RF3 portfolio the same rebalancing period should be chosen:"""

rf4 = ok.Portfolio(
    assets=assets, weights=weights, rebalancing_strategy=ok.Rebalance(period="year"), symbol="RF4_portfolio.PF"
)  # we also give a custom name to portfolio with 'symbol' propety
rf4

"""Now we create an AssetList to compare RF3 with RF4 and add a benchamrk (SP 500 TR index)."""

ls = ok.AssetList(["SP500TR.INDX", rf3, rf4])
ls

"""Some behavior will be seen with `wealth_indexes`:"""

ls.wealth_indexes.plot();

"""It worth plotting the portfolios and benchmark on the risk / return chart with `plot_assets`.<br>
**X-axis** is Risk (Standard Deviation)
**Y-axis** is Return (Mean return or CAGR)
"""

ls.plot_assets(kind="cagr");  #  set Y-axis to CAGR by kind='cagr'

"""**See [04 efficient frontier single period.ipynb](https://github.com/mbk-dev/okama/blob/master/examples/04%20efficient%20frontier%20single%20period.ipynb) and [05 efficient frontier multi-period.ipynb](https://github.com/mbk-dev/okama/blob/master/examples/05%20efficient%20frontier%20multi-period.ipynb) to plot portfolios with the Efficient Frontier.**

Given risk-free rate it's easy to compare **Sharpe Ratios** of the portfolios and match it with the benchmark with `get_sharpe_ratio`:
"""

ls.get_sharpe_ratio(rf_return=0.02)  # Risk-Free rate is 2% here

"""Most important information can be seen for trailing periods with `describe` method.  
It shows "descriptive statistics":  

- YTD (Year To date) compound return
- CAGR for a given list of periods and full available period
- Annualized mean rate of return (arithmetic mean)
- LTM Dividend yield - last twelve months dividend yield

Risk metrics (full period):

- risk (standard deviation)
- CVAR (timeframe is 1 year)
- max drawdowns (and dates of the drawdowns)
"""

ls.describe([1, 5, 8])  # portfolio CAGR is shown for YTD, 1, 5, 8 years and for the full histrical period.

"""### Forecast portfolios performance

Forecasting methods are described in a dedicated notebook [07 forecasting.ipynb](https://github.com/mbk-dev/okama/blob/master/examples/07%20forecasting.ipynb).
"""